spring.data.mongodb.uri=mongodb+srv://cloudshareuser:CloudShare%40123@cluster0.axqheia.mongodb.net/cloudshare?retryWrites=true&w=majority&appName=Cluster0

server.servlet.context-path=/api/v1.0

#spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://comic-turtle-10.clerk.accounts.dev
clerk.jwks-url=https://comic-turtle-10.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=sk_test_LMM3t2H5g7mP8h7YoibDarSWiPOgyEOVgWx0RxlGMR

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=rzp_test_vn6njrEdyg8Rp1
razorpay.key.secret=FY2P1y2162MScPaXmcWPbd8H